Codificación del codigo css para el footer
D-Ghoost/catch_page pull request #6
Opened 2023-09-05 00:22 UTC by nisbero

Buenas noches, estimado Fantasmin 
Entrego mi progreso con el código CSS y algunos cambio que realice al HTML para poder cumplir las condiciones para movile, está pendiente realizar los links de las imágenes, pero hay algo que debemos definir primero en la reunión, quedo pendiente a sus comentarios.

2023-09-07 02:33 UTC, D-Ghoost requested changes
Revisar el punto comentado y finalizar lo pendiente que se tenga.

2023-09-07 02:33 UTC, D-Ghoost commented on src/style/style.css
> +    color: #FFFBE7;
Utilizar variables

2023-09-20 03:13 UTC, nisbero commented
Se realizan los ajustes solicitados según lo acordado en la reunión.

2023-09-22 03:03 UTC, D-Ghoost requested changes
Solo falta resolver los estilos en 768px para cerrar merge

2023-09-26 02:14 UTC, merged