Creacion navbar mobil y desk con inicio
D-Ghoost/catch_page pull request #7
Opened 2023-09-07 02:53 UTC by D-Ghoost

Adelantos de navbar tanto en mobil como desk, todavia incompleto y finalización de la sección de inicio.

2023-09-07 02:54 UTC, D-Ghoost commented
Si tienen ideas de como poner el navbar sobre la imagen de inicio soy todo oidos :smile:

2023-09-12 02:18 UTC, Jusky98 requested changes
Adicional, corregir tambien el tamano del texto eslogan

2023-09-12 02:18 UTC, Jusky98 commented on src/style/style.css
>  .navdesk__logo h1{
Ajustar tamanio de titulo de acuerdo a la referencia en figma para desktop

2023-09-12 02:18 UTC, Jusky98 commented on src/style/style.css
>  .navdesk__list li{
Ajustar tamanio de listado de acuerdo a la referencia en figma para desktop

2023-10-19 00:04 UTC, merged